#!/bin/bash       
TOP_LEVEL_DIRECTORY=$(pwd)
SCENARIO_NUMBER=1
while [ $SCENARIO_NUMBER -le 270 ]; do
	mkdir "Scenario$SCENARIO_NUMBER"
	cd "Scenario$SCENARIO_NUMBER"
	
	# Determine complexity
	INTEGER=$((SCENARIO_NUMBER/90))
	FRACTION=$((SCENARIO_NUMBER%90))
	if [ \( $INTEGER -eq 0 -a $FRACTION -gt 0 \) -o \( $INTEGER -eq 1 -a $FRACTION -eq 0 \) ]; then
		ENV_COMPLEXITY=1
		NUM_PLAYERS=2
		NUMERATOR=90
	elif [ \( $INTEGER -eq 1 -a $FRACTION -gt 0 \) -o \( $INTEGER -eq 2 -a $FRACTION -eq 0 \) ]; then
		ENV_COMPLEXITY=2
		NUM_PLAYERS=4
		NUMERATOR=180
	else
		ENV_COMPLEXITY=3
		NUM_PLAYERS=8
		NUMERATOR=270
	fi

	#Determine agent type
	if [ $SCENARIO_NUMBER -ge $((NUMERATOR-90)) -a $SCENARIO_NUMBER -le $(((NUMERATOR-90)+45)) ]; then
		AGENT_TYPE=2
		AGENT_TYPE_START=$((NUMERATOR-90))
	else
		AGENT_TYPE=3
		AGENT_TYPE_START=$((NUMERATOR-45))
	fi

	#Determine episodic memory size
	if [ $SCENARIO_NUMBER -ge $AGENT_TYPE_START -a $SCENARIO_NUMBER -le $(($AGENT_TYPE_START+9)) ]; then
		EPISODIC_MEMORY_SIZE=6
	elif [ $SCENARIO_NUMBER -ge $AGENT_TYPE_START -a $SCENARIO_NUMBER -le $(($AGENT_TYPE_START+18)) ]; then
		EPISODIC_MEMORY_SIZE=8
	elif [ $SCENARIO_NUMBER -ge $AGENT_TYPE_START -a $SCENARIO_NUMBER -le $(($AGENT_TYPE_START+27)) ]; then
		EPISODIC_MEMORY_SIZE=10
	elif [ $SCENARIO_NUMBER -ge $AGENT_TYPE_START -a $SCENARIO_NUMBER -le $(($AGENT_TYPE_START+36)) ]; then
		EPISODIC_MEMORY_SIZE=12
	elif [ $SCENARIO_NUMBER -ge $AGENT_TYPE_START -a $SCENARIO_NUMBER -le $(($AGENT_TYPE_START+45)) ]; then
		EPISODIC_MEMORY_SIZE=14
	fi


	#Determine discount rate
	FRACTION=$((SCENARIO_NUMBER%9))
	case $FRACTION in
		1)
			DISCOUNT_RATE=0.1;;
		2)
			DISCOUNT_RATE=0.2;;
		3)
			DISCOUNT_RATE=0.3;;
		4)
			DISCOUNT_RATE=0.4;;
		5)
			DISCOUNT_RATE=0.5;;
		6)
			DISCOUNT_RATE=0.6;;
		7)
			DISCOUNT_RATE=0.7;;
		8)
			DISCOUNT_RATE=0.8;;
		0)
			DISCOUNT_RATE=0.9;;
	esac

	cp "$TOP_LEVEL_DIRECTORY/EnvComplexity$ENV_COMPLEXITY.txt" "$TOP_LEVEL_DIRECTORY/Scenario${SCENARIO_NUMBER}/Scenario${SCENARIO_NUMBER}Settings.txt"
	cat "$TOP_LEVEL_DIRECTORY/../AgentType$AGENT_TYPE.txt" >> "$TOP_LEVEL_DIRECTORY/Scenario${SCENARIO_NUMBER}/Scenario${SCENARIO_NUMBER}Settings.txt"
	echo -e "\n\ndiscount-rate\n0:$DISCOUNT_RATE\n\nmax-length-of-episodic-memory\n0:$EPISODIC_MEMORY_SIZE" >> "$TOP_LEVEL_DIRECTORY/Scenario${SCENARIO_NUMBER}/Scenario${SCENARIO_NUMBER}Settings.txt"
	sed -i "s/create-chrest-turtles/create-chrest-turtles $NUM_PLAYERS/g" "$TOP_LEVEL_DIRECTORY/Scenario${SCENARIO_NUMBER}/Scenario${SCENARIO_NUMBER}Settings.txt"
	let MAX_TURTLE_ID=NUM_PLAYERS-1
	sed -i "s/0:/(0-$MAX_TURTLE_ID):/g" "$TOP_LEVEL_DIRECTORY/Scenario${SCENARIO_NUMBER}/Scenario${SCENARIO_NUMBER}Settings.txt"

	REPEAT_NUMBER=1
	while [ $REPEAT_NUMBER -le 10 ]; do
		mkdir "Repeat$REPEAT_NUMBER"
		touch "Repeat$REPEAT_NUMBER/blankSoGitPicksUpDirectory$REPEAT_NUMBER.txt"
		let REPEAT_NUMBER=REPEAT_NUMBER+1
	done
	cd "$TOP_LEVEL_DIRECTORY"
	let SCENARIO_NUMBER=SCENARIO_NUMBER+1
done
